In [1]:
import pandas as pd 
import os

In [2]:
default_path = os.getcwd()
data_path = os.path.join(default_path, '../data')

In [3]:
dsm = pd.read_csv(os.path.join(data_path, 'aud_dsm_label2.csv'))
dsm

In [3]:
dsm = pd.read_csv(os.path.join(data_path, 'aud_dsm_label2.csv'))
dsm

,id,subreddit,author,text,type,time,parent_id,o_id,tok_len,label
0,t3_16v6hx,depression,[deleted],if you're lonely i am find an old age pensione...,comment,1.358599e+09,t1_c7zo83f,c7zpy8m,21,0
1,t3_w6zaa,depression,throw13away,One thing that stuck out in my mind from the N...,comment,1.341807e+09,t3_w6zaa,c5bc8t2,27,0
2,t3_95ezhs,depression,pinkwav,"i feel like there's a fine line between ""depre...",comment,1.544300e+09,t1_ebcmg0f,ebdlcmq,15,0
3,t3_7djepe,depression,EchoJunior,Just so fucking lonely,comment,1.510909e+09,t3_7djepe,dpy9r4f,4,0
4,t3_95ezhs,depression,pinkwav,"i feel like lazy people have a choice, depress...",comment,1.544300e+09,t1_ebcmg0f,ebdlcmq,18,0
...,...,...,...,...,...,...,...,...,...,...
1625664,t3_cg86fe,depression,oneandonlyODIN,My head canon is that society has to keep suic...,comment,1.563768e+09,t1_eufa712,eufbg10,36,8
1625665,9q1pxm,depression,PelicanWithAnAxe,"Family finally started giving a shit about me,...",post,1.540107e+09,9q1pxm,9q1pxm,25,8
1625666,2txoxu,depression,[deleted],I have been suicidal for the last 7 months and...,post,1.422425e+09,2txoxu,2txoxu,17,8
1625667,5ovcva,depression,Maes4577,Lightly suicidal,title,1.484812e+09,5ovcva,5ovcva,2,8
1625668,9q1pxm,depression,PelicanWithAnAxe,Even though I still want to kill myself,post,1.540107e+09,9q1pxm,9q1pxm,8,8

In [11]:
dsm

,id,subreddit,author,text,type,time,parent_id,o_id,tok_len,label
0,t3_16v6hx,depression,[deleted],if you're lonely i am find an old age pensione...,comment,1.358599e+09,t1_c7zo83f,c7zpy8m,21,0
1,t3_w6zaa,depression,throw13away,One thing that stuck out in my mind from the N...,comment,1.341807e+09,t3_w6zaa,c5bc8t2,27,0
2,t3_95ezhs,depression,pinkwav,"i feel like there's a fine line between ""depre...",comment,1.544300e+09,t1_ebcmg0f,ebdlcmq,15,0
3,t3_7djepe,depression,EchoJunior,Just so fucking lonely,comment,1.510909e+09,t3_7djepe,dpy9r4f,4,0
4,t3_95ezhs,depression,pinkwav,"i feel like lazy people have a choice, depress...",comment,1.544300e+09,t1_ebcmg0f,ebdlcmq,18,0
...,...,...,...,...,...,...,...,...,...,...
1625664,t3_cg86fe,depression,oneandonlyODIN,My head canon is that society has to keep suic...,comment,1.563768e+09,t1_eufa712,eufbg10,36,8
1625665,9q1pxm,depression,PelicanWithAnAxe,"Family finally started giving a shit about me,...",post,1.540107e+09,9q1pxm,9q1pxm,25,8
1625666,2txoxu,depression,[deleted],I have been suicidal for the last 7 months and...,post,1.422425e+09,2txoxu,2txoxu,17,8
1625667,5ovcva,depression,Maes4577,Lightly suicidal,title,1.484812e+09,5ovcva,5ovcva,2,8
1625668,9q1pxm,depression,PelicanWithAnAxe,Even though I still want to kill myself,post,1.540107e+09,9q1pxm,9q1pxm,8,8

In [19]:
dsm[dsm.text==dsm_tmp.text[0]].index.values[0]

329282

In [20]:
idx_list = []

for idx in range(len(dsm_tmp)):
    idx_list.append(dsm[dsm.text==dsm_tmp.text[idx]].index.values[0])

print(len(idx_list))

9000

In [23]:
len(dsm)

1625669

In [24]:
dsm.drop(idx_list, inplace=True)

In [25]:
len(dsm)

1616687

In [4]:
count_df = dsm.groupby('label').count()
count_df = count_df[['id']]
count_df.columns = ['count']
count_df

        count
label
0      515596
1      186424
2       55527
3      180213
4       37161
5       19371
6      258203
7       73640
8      299534

In [26]:
a1_df = dsm[dsm.label==0]
a2_df = dsm[dsm.label==1]
a3_df = dsm[dsm.label==2]
a4_df = dsm[dsm.label==3]
a5_df = dsm[dsm.label==4]
a6_df = dsm[dsm.label==5]
a7_df = dsm[dsm.label==6]
a8_df = dsm[dsm.label==7]
a9_df = dsm[dsm.label==8]

In [27]:
a1_df.reset_index(inplace=True, drop=True)
a2_df.reset_index(inplace=True, drop=True)
a3_df.reset_index(inplace=True, drop=True)
a4_df.reset_index(inplace=True, drop=True)
a5_df.reset_index(inplace=True, drop=True)
a6_df.reset_index(inplace=True, drop=True)
a7_df.reset_index(inplace=True, drop=True)
a8_df.reset_index(inplace=True, drop=True)
a9_df.reset_index(inplace=True, drop=True)

In [28]:
a9_df

,id,subreddit,author,text,type,time,parent_id,o_id,tok_len,label
0,9q1q3e,depression,HopelessRoomful,"I'm pathetic honestly, I'm lucky I'm born as w...",post,1.540107e+09,9q1q3e,9q1q3e,33,8
1,efkxj1,depression,[deleted],I cant stop panicking I am terrified my only c...,title,1.577304e+09,efkxj1,efkxj1,16,8
2,t3_2c07ad,depression,SoapSamich,"I'm not a likable person but then again, why w...",comment,1.406642e+09,t1_cjap5xu,cjayxme,24,8
3,t3_a4bgad,depression,Bogus234e,"I eventually realized I wasn't suicidal, but O...",comment,1.544299e+09,t3_a4bgad,ebdl3mm,19,8
4,t3_5fgd70,depression,Gracie_Dee_,"I don't want to die, but living is hell",comment,1.480536e+09,t3_5fgd70,damidkl,11,8
...,...,...,...,...,...,...,...,...,...,...
298622,t3_2c0t4f,depression,glendon24,I've dealt with depression for 31 years now an...,comment,1.406640e+09,t3_2c0t4f,cjay86h,19,8
298623,t3_cg86fe,depression,oneandonlyODIN,My head canon is that society has to keep suic...,comment,1.563768e+09,t1_eufa712,eufbg10,36,8
298624,9q1pxm,depression,PelicanWithAnAxe,"Family finally started giving a shit about me,...",post,1.540107e+09,9q1pxm,9q1pxm,25,8
298625,2txoxu,depression,[deleted],I have been suicidal for the last 7 months and...,post,1.422425e+09,2txoxu,2txoxu,17,8
298626,5ovcva,depression,Maes4577,Lightly suicidal,title,1.484812e+09,5ovcva,5ovcva,2,8

In [8]:
a9_df.text.loc[34044]

"In the meantime, we have some resources it's more geared toward suicidal thoughts and impulses, but it might be helpful"

In [9]:
a2_df.sort_values('tok_len')

,id,subreddit,author,text,type,time,parent_id,o_id,tok_len,label
64107,5gvwf0,depression,GreenDevour,interests,post,1.481063e+09,5gvwf0,5gvwf0,1,1
74077,t3_11z4p6,depression,RainyDayDaydream,pleasure,comment,1.351038e+09,t1_c6qsmt9,c6qsqoy,1,1
72456,5ilt3g,depression,StickManTwit,excitement,post,1.481855e+09,5ilt3g,5ilt3g,1,1
130119,t3_40hbhk,depression,makkus1,interest,comment,1.452529e+09,t1_cyu4ntx,cyu51el,1,1
127019,b3ms8p,depression,evanamyl,fulfillment,post,1.553146e+09,b3ms8p,b3ms8p,1,1
...,...,...,...,...,...,...,...,...,...,...
183674,9p3yxp,depression,IDemandCoffee,And though I know the girl I was talking to to...,post,1.539820e+09,9p3yxp,9p3yxp,40,1
16898,t3_cys5h,depression,throwoutgirl,I'm sure you're feeling a need to interact wit...,comment,1.281293e+09,t3_cys5h,c0wa1n2,40,1
117734,t3_q4hj5,depression,anassakata,"I suppose spending more time with my friends, ...",comment,1.330121e+09,t1_c3uo4l4,c3uok6b,40,1
145205,t3_2pfd0a,depression,rollingthunderbolt,One of the reasons I flunked out of college wa...,comment,1.418698e+09,t3_2pfd0a,cmw6cgo,40,1
147887,t3_5aswoy,depression,FijiFlow,"you actually do get a hangover from weed, also...",comment,1.478148e+09,t1_d9jekfo,d9jjd2j,40,1

In [29]:
a1_samp = a1_df.sample(1000)
a2_samp = a2_df.sample(1000)
a3_samp = a3_df.sample(1000)
a4_samp = a4_df.sample(1000)
a5_samp = a5_df.sample(1000)
a6_samp = a6_df.sample(1000)
a7_samp = a7_df.sample(1000)
a8_samp = a8_df.sample(1000)
a9_samp = a9_df.sample(1000)

In [30]:
dsm_samp = pd.concat([a1_samp, a2_samp, a3_samp, a4_samp, a5_samp, a6_samp, a7_samp, a8_samp, a9_samp])
dsm_samp.reset_index(inplace=True, drop=True)
dsm_samp

,id,subreddit,author,text,type,time,parent_id,o_id,tok_len,label
0,41r0lb,depression,Throwaway_987653,I have been depressed for three years now and ...,post,1.453241e+09,41r0lb,41r0lb,17,0
1,t3_4trofu,depression,HiMyNameIsBoard,"Haha believe it or not, some people are actual...",comment,1.469038e+09,t1_d5ju5e4,d5jus1e,20,0
2,8ued2h,depression,mahiloa,My boyfriend is depressed manic??,title,1.530142e+09,8ued2h,8ued2h,7,0
3,9ghem0,depression,Doesntdream,"I'm depressed I'm a horrible person, who doesn...",post,1.537160e+09,9ghem0,9ghem0,14,0
4,7s2m0x,depression,CupofGravitea,Im feeling so incredibly depressed right now t...,post,1.516588e+09,7s2m0x,7s2m0x,32,0
...,...,...,...,...,...,...,...,...,...,...
8995,1qvhbu,depression,Hedonistic_Existence,"And then it will drop, like a cosine curve, an...",post,1.384749e+09,1qvhbu,1qvhbu,35,8
8996,2c13fb,depression,[deleted],Tldr Lack of medical support during my obligat...,post,1.406627e+09,2c13fb,2c13fb,23,8
8997,t3_4ie7nf,depression,SummerFloyd,It makes me even more suicidal,comment,1.462733e+09,t1_d2xm561,d2xojem,6,8
8998,4l6lbs,depression,shesacrackerjack,"When I'm not feeling all of this, when I get a...",post,1.464286e+09,4l6lbs,4l6lbs,38,8
8999,t3_83rzcy,depression,pghdepressed,"Because of that, I made friends online and we ...",comment,1.520862e+09,t1_dvkm5qb,dvko2dk,40,8

In [31]:
dsm_samp.to_csv(os.path.join(data_path, 'dsm_samp_1000_02.csv'), index=False)

In [10]:
dsm_tmp = pd.read_csv(os.path.join(data_path, 'dsm_samp_1000.csv'))
dsm_tmp

,id,subreddit,author,text,type,time,parent_id,o_id,tok_len,label
0,t3_5kwodh,depression,Iluvmychildren,"I am not depressed right now, but I say to may...",comment,1.483034e+09,t3_5kwodh,dbrghop,14,0
1,5vopn7,depression,derpynarwhal9,I'm twenty five and the earliest I can for sur...,post,1.487830e+09,5vopn7,5vopn7,17,0
2,t3_9boomi,depression,Belial42069,This whole subreddit is built around talking b...,comment,1.535674e+09,t3_9boomi,e54l8nt,10,0
3,t3_8ftokj,depression,r0587321,If you do not have what it takes to do this gt...,comment,1.525033e+09,t1_dy6epan,dy6f3rl,28,0
4,t3_bsqy2,depression,GGINQUISITOR,If you're lonely and want companionship get a ...,comment,1.272482e+09,t3_bsqy2,c0p1cw8,13,0
...,...,...,...,...,...,...,...,...,...,...
8995,bf8h3x,depression,[deleted],anyone else go from being fine to suicidal in ...,title,1.555735e+09,bf8h3x,bf8h3x,14,8
8996,t3_ai69aj,depression,haklana,"I deal with a lot of my own suicidal thoughts,...",comment,1.548045e+09,t3_ai69aj,eelhauk,25,8
8997,4d2ix7,depression,GottaGetDatTHrowaway,"I wish I could kill myself, or cut or something",post,1.459620e+09,4d2ix7,4d2ix7,11,8
8998,anwpxe,depression,throwaway10031998,We all die so might as well make this life the...,post,1.549493e+09,anwpxe,anwpxe,21,8
8999,2mcfoi,depression,H1TMAN290,I was just really worried and didn't want her ...,post,1.416019e+09,2mcfoi,2mcfoi,12,8

### DeepL doc

In [32]:
dsm_dl = dsm_samp.copy()
dsm_dl = dsm_dl[['text']]
dsm_dl

                                                   text
0     I have been depressed for three years now and ...
1     Haha believe it or not, some people are actual...
2                     My boyfriend is depressed manic??
3     I'm depressed I'm a horrible person, who doesn...
4     Im feeling so incredibly depressed right now t...
...                                                 ...
8995  And then it will drop, like a cosine curve, an...
8996  Tldr Lack of medical support during my obligat...
8997                     It makes me even more suicidal
8998  When I'm not feeling all of this, when I get a...
8999  Because of that, I made friends online and we ...

[9000 rows x 1 columns]

In [33]:
dsm_dl.to_csv(os.path.join(data_path, 'dsm_dl_1000_02.csv'), index=False)