In [1]:
from sklearn.model_selection import KFold
import pandas as pd 
import numpy as np
import random
import os

In [17]:
default_path = os.getcwd()
data_path = os.path.join(default_path, '../data/BWS/score')
base_model = os.path.join(default_path, '../base-model')
config_path = os.path.join(default_path, '../config')
log_path = os.path.join(default_path, '../log')
model_path = os.path.join(default_path, '../model')
config_file = "bert-base.json"

In [18]:
criteria = 4

In [19]:
data_train = pd.read_csv(os.path.join(data_path, f'bws_a{criteria}_score_train.csv'))
data_val = pd.read_csv(os.path.join(data_path, f'bws_a{criteria}_score_val.csv'))
data_test = pd.read_csv(os.path.join(data_path, f'bws_a{criteria}_score_test.csv'))

In [20]:
data_trainset = pd.concat([data_train, data_val])
data_trainset.head(3)

,text,text_kor,label
0,"I often think ""what if I am just lazy"" but in...","나는 종종 ""그냥 게으르면 어떨까""라고 생각하지만, 실제로는 뇌가 거슬리는 생각으로...",7
1,The only thing is when i go home I drink my se...,유일한 것은 집에 가면 술을 마시고 잠을 자는 것이다. 왜냐하면 나는 내 인생에서 ...,3
2,I couldnt sleep at all because I didnt have my...,불면증 약이 없어서 잠을 전혀 못 잤어요,10

In [21]:
data_trainset.reset_index(drop=True, inplace=True)

In [22]:
kf = KFold(n_splits=4)
kf.get_n_splits(data_trainset)

4

In [23]:
data_test

,text,text_kor,label
0,So I need to sleep if any1 leaves any comment...,그래서 나는 만약 누군가가 이번에 댓글을 남기면 잠을 자야 한다. 고마워 그리고 나...,1
1,I woke up pretty early and could not sleep so...,나는 꽤 일찍 일어나서 잠을 잘 수가 없어서 일어나서 대신 선형대수학 공부를 했다,0
2,Im on 300mg twice of lithium 75mg effexor twi...,나는 300mg의 리튬 75mg의 에펙스를 두 번 또는 하루에 두 번 복용하고 필요...,7
3,I was sleeping about 12 hours a day never wan...,"나는 하루에 12시간 정도 자고 있었고, 여러 번 자살로 간주되는 내 방을 떠나고 ...",8
4,Im just going to try to sleep,나는 그냥 자려고 노력할 것이다,3
...,...,...,...
315,That is why I look forward to sleeping,그게 내가 자는 것을 기대하는 이유이다,3
316,When someone is tired they usually sleep they...,누군가가 피곤할 때 그들은 보통 잠을 잔다. 그들은 그것이 존재하기 때문에 가능한 ...,6
317,All I want to do is sleep all day,내가 하고 싶은 것은 하루 종일 자는 것이다,2
318,I am bored and want to avoid sleeping again bu...,나는 지루하고 다시 자는 것을 피하고 싶지만 모든 것이 너무 힘이 드는 것 같아서 ...,6
319,It will make the urge to sleep all the time go...,그것은 결국 항상 자고 싶은 충동을 사라지게 할 것이다,6

In [24]:
data_fold_train_dict = dict(); data_fold_test_dict = dict()

for i, (train_index, test_index) in enumerate(kf.split(data_trainset)):
    data_fold_train_dict[f'fold_{i}'] = train_index
    data_fold_test_dict[f'fold_{i}'] = test_index 
    print(f'fold {i}')
    print(f"Train: index={len(train_index)}")
    print(f"Test:  index={len(test_index)}", end='\n\n')

fold 0
Train: index=960
Test:  index=320

fold 1
Train: index=960
Test:  index=320

fold 2
Train: index=960
Test:  index=320

fold 3
Train: index=960
Test:  index=320

In [25]:
data_fold1_train = data_trainset.loc[data_fold_train_dict['fold_0']]; data_fold1_test = data_trainset.loc[data_fold_test_dict['fold_0']]
data_fold2_train = data_trainset.loc[data_fold_train_dict['fold_1']]; data_fold2_test = data_trainset.loc[data_fold_test_dict['fold_1']]
data_fold3_train = data_trainset.loc[data_fold_train_dict['fold_2']]; data_fold3_test = data_trainset.loc[data_fold_test_dict['fold_2']]
data_fold4_train = data_trainset.loc[data_fold_train_dict['fold_3']]; data_fold4_test = data_trainset.loc[data_fold_test_dict['fold_3']]

In [26]:
data_fold1_test

,text,text_kor,label
0,"I often think ""what if I am just lazy"" but in...","나는 종종 ""그냥 게으르면 어떨까""라고 생각하지만, 실제로는 뇌가 거슬리는 생각으로...",7
1,The only thing is when i go home I drink my se...,유일한 것은 집에 가면 술을 마시고 잠을 자는 것이다. 왜냐하면 나는 내 인생에서 ...,3
2,I couldnt sleep at all because I didnt have my...,불면증 약이 없어서 잠을 전혀 못 잤어요,10
3,I often sleep during the daytime because I am ...,나는 너무 피곤해서 밤이 될 때까지 깨어 있을 수 없을 것 같아서 낮에 자주 잔다,5
4,The first few nights alone I just did not kno...,처음 며칠 밤은 혼자서 잠을 잘 수가 없었다,6
...,...,...,...
315,The first day I took it at 2pm and felt sedate...,첫 날 오후 2시에 그것을 복용하고 베니드릴을 먹은 것처럼 진정되었지만 그날 밤에는...,6
316,I wanted to see if I could figure out writing ...,나는 내가 프롬프트를 쓰는 것에 대해 알아낼 수 있는지 알아보고 싶었다. 그리고 우...,7
317,My parents used to complain about how i stay u...,"우리 부모님은 내가 어떻게 깨어 있는지에 대해 불평하곤 했는데, 내가 잠을 잘 수 ...",3
318,It feels so good to lay in that warm cozy be...,그 따뜻하고 포근한 침대에 누우니 기분이 너무 좋은데 1시간만 자고 일이 싫어지더라...,2
319,That night my friend booked another night at ...,그날 밤 내 친구는 6번 모텔에서 하룻밤을 더 예약했는데 이번에는 침실이 하나여서 ...,1

In [27]:
data_fold1_train.to_csv(os.path.join(data_path, f'a{criteria}_fold1_train.csv'), index=False)
data_fold1_test.to_csv(os.path.join(data_path, f'a{criteria}_fold1_test.csv'), index=False)
data_fold2_train.to_csv(os.path.join(data_path, f'a{criteria}_fold2_train.csv'), index=False)
data_fold2_test.to_csv(os.path.join(data_path, f'a{criteria}_fold2_test.csv'), index=False)
data_fold3_train.to_csv(os.path.join(data_path, f'a{criteria}_fold3_train.csv'), index=False)
data_fold3_test.to_csv(os.path.join(data_path, f'a{criteria}_fold3_test.csv'), index=False)
data_fold4_train.to_csv(os.path.join(data_path, f'a{criteria}_fold4_train.csv'), index=False)
data_fold4_test.to_csv(os.path.join(data_path, f'a{criteria}_fold4_test.csv'), index=False)