In [1]:
import pandas as pd 
import os

In [436]:
default_path = os.getcwd()
data_path = os.path.join(default_path, '../data', 'BWS')

In [772]:
file_name = 'a9_bws_translated.csv'

In [773]:
data = pd.read_csv(os.path.join(data_path, file_name))
data

,id,subreddit,author,text,type,time,parent_id,o_id,tok_len,label,group_a,group_b,group_c,translated
0,8aemf3,depression,[deleted],Welcome aboard for another session of free rei...,post,1.523063e+09,8aemf3,8aemf3,23,8,True,False,False,"근거 없는 슬픔과 절망감, 알코올 중독 자해와 자살 생각의 자유 통치 불안의 또 다..."
1,12ao7l,depression,katekiedis,I was not suicidal and never have been but I j...,post,1.351543e+09,12ao7l,12ao7l,22,8,True,False,False,나는 자살한 적이 없었고 결코 그런 적이 없었지만 나는 그저 내 자신이 아니며 몇 ...
2,t3_4gc204,depression,ZzZlostZzZ,We might cease to exist as individuals but co...,comment,1.461578e+09,t3_4gc204,d2gd2j8,24,8,True,False,False,우리는 개인으로 존재하는 것을 멈출 수 있지만 의식은 계속되고 장기적으로 누가 누구...
3,t3_b37ruw,depression,RedTrog11,Once you kill yourself you can not take it back,comment,1.553058e+09,t3_b37ruw,eixrofr,10,8,True,False,False,한 번 자살하면 되돌릴 수 없다
4,a8qzx6,depression,SixthUnderminer,To me the voice of reason to kill myself has ...,post,1.545532e+09,a8qzx6,a8qzx6,21,8,True,False,False,나에게 자살해야 할 이유의 목소리는 더 많은 이유와 함께 더 커졌다
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,30c20w,depression,tip125,I have had panic attacks suicidal thoughts a...,post,1.427341e+09,30c20w,30c20w,14,8,True,False,False,나는 자살 생각으로 공황 발작을 겪었고 절망적이다
1196,t3_cml6ni,depression,nyxiecat,I want to disappear fade away from existence,comment,1.567742e+09,t3_cml6ni,ez8g3uy,9,8,True,False,False,나는 존재에서 희미하게 사라지고 싶다
1197,2m3w0s,depression,Rattleh3ad,All I want is to just die,post,1.415825e+09,2m3w0s,2m3w0s,7,8,True,False,False,내가 원하는 건 그냥 죽는 거야
1198,29v50c,depression,Thingsandstuff22,I really do wish I was alone sometimes so that...,post,1.404519e+09,29v50c,29v50c,18,8,True,False,False,가족을 해치지 않고 스스로 목숨을 끊을 수 있도록 가끔은 내가 혼자였으면 좋겠다
1199,5ujens,depression,AkaLittleKing,Or that I had the balls to disappear,post,1.487295e+09,5ujens,5ujens,8,8,True,False,False,아니면 내가 사라질 배짱이 있었다는 것도

In [774]:
data[data.text.str[-1] == '9'].head(3)

Empty DataFrame
Columns: [id, subreddit, author, text, type, time, parent_id, o_id, tok_len, label, group_a, group_b, group_c, translated]
Index: []

In [775]:
data.text = data.text.apply(lambda x: x.replace('.', ''))

In [776]:
import numpy as np

last_w = list(np.unique(data.text.str[-1]))
last_w[:3]

[' ', '!', '"']

In [777]:
non_alpha = [w for w in last_w if not w.isalpha()]
non_numeric = [w for w in non_alpha if not w.isnumeric()]

non_numeric

[' ', '!', '"', '?']

In [778]:
def convert_txt(text):
    if text[-1] in non_numeric:
        return text
    return text + '.'

In [779]:
data.text = data.text.apply(convert_txt)
data

,id,subreddit,author,text,type,time,parent_id,o_id,tok_len,label,group_a,group_b,group_c,translated
0,8aemf3,depression,[deleted],Welcome aboard for another session of free rei...,post,1.523063e+09,8aemf3,8aemf3,23,8,True,False,False,"근거 없는 슬픔과 절망감, 알코올 중독 자해와 자살 생각의 자유 통치 불안의 또 다..."
1,12ao7l,depression,katekiedis,I was not suicidal and never have been but I j...,post,1.351543e+09,12ao7l,12ao7l,22,8,True,False,False,나는 자살한 적이 없었고 결코 그런 적이 없었지만 나는 그저 내 자신이 아니며 몇 ...
2,t3_4gc204,depression,ZzZlostZzZ,We might cease to exist as individuals but co...,comment,1.461578e+09,t3_4gc204,d2gd2j8,24,8,True,False,False,우리는 개인으로 존재하는 것을 멈출 수 있지만 의식은 계속되고 장기적으로 누가 누구...
3,t3_b37ruw,depression,RedTrog11,Once you kill yourself you can not take it back.,comment,1.553058e+09,t3_b37ruw,eixrofr,10,8,True,False,False,한 번 자살하면 되돌릴 수 없다
4,a8qzx6,depression,SixthUnderminer,To me the voice of reason to kill myself has ...,post,1.545532e+09,a8qzx6,a8qzx6,21,8,True,False,False,나에게 자살해야 할 이유의 목소리는 더 많은 이유와 함께 더 커졌다
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,30c20w,depression,tip125,I have had panic attacks suicidal thoughts a...,post,1.427341e+09,30c20w,30c20w,14,8,True,False,False,나는 자살 생각으로 공황 발작을 겪었고 절망적이다
1196,t3_cml6ni,depression,nyxiecat,I want to disappear fade away from existence.,comment,1.567742e+09,t3_cml6ni,ez8g3uy,9,8,True,False,False,나는 존재에서 희미하게 사라지고 싶다
1197,2m3w0s,depression,Rattleh3ad,All I want is to just die.,post,1.415825e+09,2m3w0s,2m3w0s,7,8,True,False,False,내가 원하는 건 그냥 죽는 거야
1198,29v50c,depression,Thingsandstuff22,I really do wish I was alone sometimes so that...,post,1.404519e+09,29v50c,29v50c,18,8,True,False,False,가족을 해치지 않고 스스로 목숨을 끊을 수 있도록 가끔은 내가 혼자였으면 좋겠다
1199,5ujens,depression,AkaLittleKing,Or that I had the balls to disappear.,post,1.487295e+09,5ujens,5ujens,8,8,True,False,False,아니면 내가 사라질 배짱이 있었다는 것도

In [780]:
data.to_csv(os.path.join(data_path, file_name), index=False)