In [1]:
import pandas as pd 
import os

In [32]:
default_path = os.getcwd()
base_model = 'C:/Users/lamda/Desktop/LAMDA_git/EmoDep/base-model'
config_path = 'C:/Users/lamda/Desktop/LAMDA_git/EmoDep/config'
model_path = "C:/Users/lamda/Desktop/LAMDA_git/EmoDep/model/emodep/"
data_path = "C:/Users/lamda/Desktop/LAMDA_git/EmoDep/data/EmoDep/"
config_file = "bert-base.json"
save_path = os.path.join(default_path, './')

In [96]:
criteria = 9
emodep = pd.read_csv(os.path.join(data_path, f'emodep_a{criteria}.csv'))

In [97]:
trans_data = 'C:/Users/lamda/Desktop/LAMDA_git/chatgpt/data'

In [98]:
trans = pd.read_csv(os.path.join(trans_data, f'emodep_a{criteria}_trans.csv'))
trans

                    그럼에도 불구하고, 나는 여전히 자살 생각을 하고 자해를 했어요.
0      I'm really sorry to hear that you're feeling t...
1      나는 내 평생 바텐더로 일할 수도 있겠지만, 그렇게 한다면 30살 전에 자살할 것 같아.
2      I'm sorry to hear that you're feeling this way...
3                                  저는 지금 일하고 있고 죽고 싶습니다.
4        I cannot even kill myself because I'm a coward.
...                                                  ...
30333  I'm sorry to hear that you're feeling this way...
30334  나는 이게 이기적인 것을 알지만, 죽고 싶다는 대신에 나는 아무도 차이를 모를테니까...
30335  I have a friend who has been depressed, border...
30336                                나는 심지어 자살할 의지조차 없어.
30337  I'm really sorry to hear that you're feeling t...

[30338 rows x 1 columns]

In [99]:
head = trans.columns.values.tolist()   # 마지막 데이터 
trans.columns = ['text']
trans

                                                    text
0      I'm really sorry to hear that you're feeling t...
1      나는 내 평생 바텐더로 일할 수도 있겠지만, 그렇게 한다면 30살 전에 자살할 것 같아.
2      I'm sorry to hear that you're feeling this way...
3                                  저는 지금 일하고 있고 죽고 싶습니다.
4        I cannot even kill myself because I'm a coward.
...                                                  ...
30333  I'm sorry to hear that you're feeling this way...
30334  나는 이게 이기적인 것을 알지만, 죽고 싶다는 대신에 나는 아무도 차이를 모를테니까...
30335  I have a friend who has been depressed, border...
30336                                나는 심지어 자살할 의지조차 없어.
30337  I'm really sorry to hear that you're feeling t...

[30338 rows x 1 columns]

In [100]:
trans_data = trans.text.values.tolist()

In [101]:
tmp = trans_data + head
tmp[-1]

'그럼에도 불구하고, 나는 여전히 자살 생각을 하고 자해를 했어요.'

In [102]:
emodep['kor'] = tmp 
emodep

,author,text,type,criteria,label,time,kor
0,[deleted],I cant stop panicking I am terrified my only c...,title,8,5.17,1.577304e+09,I'm really sorry to hear that you're feeling t...
1,Wh00pity_sc00p,I mean I guess I could work as a bartender for...,post,8,5.76,1.569897e+09,"나는 내 평생 바텐더로 일할 수도 있겠지만, 그렇게 한다면 30살 전에 자살할 것 같아."
2,mrblue6,Ive got school on Monday I dont wanna go I j...,post,8,6.09,1.540110e+09,I'm sorry to hear that you're feeling this way...
3,iloveh900,I am at work right now and want to die,title,8,8.40,1.484833e+09,저는 지금 일하고 있고 죽고 싶습니다.
4,Piece_Of_Trash_,i can not even kill myself because im a coward,post,8,3.89,1.569897e+09,I cannot even kill myself because I'm a coward.
...,...,...,...,...,...,...,...
30334,extroverted_inrovert,I know it is selfish so instead of wanting to...,post,8,5.12,1.557449e+09,"나는 이게 이기적인 것을 알지만, 죽고 싶다는 대신에 나는 아무도 차이를 모를테니까..."
30335,Purfectkitten,I have a friend who for as long as I have know...,post,8,3.87,1.453042e+09,"I have a friend who has been depressed, border..."
30336,[deleted],I do not even have the willpower to kill myself,title,8,3.44,1.484803e+09,나는 심지어 자살할 의지조차 없어.
30337,zeppelinism,I feel as though I can not do it anymore and y...,post,8,8.03,1.402864e+09,I'm really sorry to hear that you're feeling t...
30338,_floof_poof,And yet I still have suicidal thoughts and I h...,post,8,8.24,1.540106e+09,"그럼에도 불구하고, 나는 여전히 자살 생각을 하고 자해를 했어요."

In [103]:
emodep.tail(3)

,author,text,type,criteria,label,time,kor
30336,[deleted],I do not even have the willpower to kill myself,title,8,3.44,1.484803e+09,나는 심지어 자살할 의지조차 없어.
30337,zeppelinism,I feel as though I can not do it anymore and y...,post,8,8.03,1.402864e+09,I'm really sorry to hear that you're feeling t...
30338,_floof_poof,And yet I still have suicidal thoughts and I h...,post,8,8.24,1.540106e+09,"그럼에도 불구하고, 나는 여전히 자살 생각을 하고 자해를 했어요."

In [104]:
emodep.to_csv(os.path.join(data_path, f'emodep_a{criteria}_trans.csv'), index=False)